sudo: false
language: ruby
cache: bundler
rvm:
#- 2.1
- 2.1.1

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
# travis encrypt 'GIT_NAME="garduini" GIT_EMAIL="geoffreyarduini@gmail.com" GH_TOKEN=jHs6tNrjH73nEzzXWpYB'
env:
  global:
    secure: "qcY5Grn3QnzYhUvPPAzrQd1SXPPD+6SFVu/yyl6STDJHWOyeNPr4dBvv/hEwyhjqJcL6U4IQRX0J1loduwaG44vf23GmP/4kreQbQrogJ6bXVY6pDkogI1CZWlTIYuEGjJ5NoRdLbQt0FDC+oxduGFiM9/C682eX2Vu2+/V/a/RQltE5IwyEm0Fu1gkOvI8SJ5zRHTpSjYnhRt5EfJ4CBX1oBupy9bojrSd/M/kVMtB4jkO5KiNmq+LM7VAkMxWG+y1cEFcn2P1CpzLPfvGjc3/sb8zIeA07BZQTP1VIka2VN9HgCVGKf81+yHLbgIJLKG6MDOZ7ieUnMzAs/CBimUkjR/87u4Vl6keGP2hfH7y79Wt6PDI0SIWJjYk6ptxQechqFdmbPpgoRCoysicVj77YBBjBBh51F4b6Ie+TGE2Tpz/HWroxhV4XJGFwn/Hqh+9HPH9qLOwKgZlf8YUs2jKXq+XuYuqPpd9HapPU1aGG1OE++hOg9szErYn3xSK2W4BiZsCzpMjvq3m/9YU4e9gCvm9mfnadPqRnDfXwSumGZayZH4ajEA7mPrZ/WqYHsUp9o9q1yYRqci2LCSpJikOGf32IqlTk99LgRcCESR0Q8Qbok+y//n3IdUe1PfaD+Xmu4YwomWy7q1Wk2BFCsy8ER3pJtAafQmpOzjYRD+M="
branches:
  only:
    - master
